import Link from 'next/link';
import { notFound } from 'next/navigation';
import { createServerSupabase } from '../../../lib/supabase';
import { reviewVerification } from './actions';
import { ReviewControls } from './review-controls';
export default async function VerificationDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createServerSupabase();
  const { data: submission } = await supabase.from('provider_verifications').select('id,status,doc_urls,note,submitted_at,reviewed_at,profiles!provider_verifications_provider_id_fkey(id,full_name,initials,provider_category,area,phone,email,provider_rating,provider_jobs_count)').eq('id', id).maybeSingle();
  if (!submission) notFound(); const provider: any = submission.profiles; const urls = submission.doc_urls ?? [];
  const signedDocs = await Promise.all(urls.map(async (path: string) => { const { data } = await supabase.storage.from('verification-docs').createSignedUrl(path, 3600); return { path, url: data?.signedUrl }; }));
  const review = reviewVerification.bind(null, id);
  return <><Link className="mono" href="/verifications">← Back to queue</Link><div className="topline" style={{ marginTop: 20 }}><div><p className="eyebrow">Verification submission</p><h1 className="heading">{provider?.full_name ?? 'Provider'}</h1><p className="intro">Submitted {new Intl.DateTimeFormat('en-GB', { dateStyle: 'long' }).format(new Date(submission.submitted_at))}</p></div><span className={`pill ${submission.status}`}>{submission.status}</span></div><div className="detail"><section className="panel"><h2>Provider record</h2><div className="facts"><div><label>Trade</label><strong>{provider?.provider_category ?? 'Not set'}</strong></div><div><label>Service area</label><strong>{provider?.area ?? 'Not set'}</strong></div><div><label>Phone</label><strong>{provider?.phone ?? 'Not provided'}</strong></div><div><label>Email</label><strong>{provider?.email ?? 'Not provided'}</strong></div><div><label>Rating</label><strong>{provider?.provider_rating?.toFixed?.(1) ?? '—'} · {provider?.provider_jobs_count ?? 0} jobs</strong></div></div><h2 style={{ marginTop: 32 }}>Submitted documents</h2><div className="docs">{signedDocs.length ? signedDocs.map(({ path, url }) => url ? <a className="doc" key={path} href={url} target="_blank">Open document<br /><span className="mono">{path.split('/').pop()}</span></a> : <div className="doc" key={path}>Document unavailable</div>) : <div className="doc">No documents were attached.</div>}</div></section><aside className="panel"><h2>Decision</h2>{submission.status === 'pending' ? <ReviewControls approve={async (_state, formData) => review('approved', formData)} reject={async (_state, formData) => review('rejected', formData)} /> : <><p>This submission was <strong>{submission.status}</strong>.</p>{submission.note && <><label>Review note</label><p>{submission.note}</p></>}</>}</aside></div></>;
}
