// Copies the legal documents (docs/legal/*.md, the one source of truth)
// into lib/legalContent.generated.ts so the public /legal pages ship them
// inside the admin bundle - a deploy never has to reach outside admin/.
// Runs before every build; the generated file is committed too, so a build
// that can't see docs/ still has the last synced copy.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, '..', '..', 'docs', 'legal');
const target = join(here, '..', 'lib', 'legalContent.generated.ts');
const files = { terms: 'terms-of-service.md', privacy: 'privacy-policy.md', refunds: 'refund-dispute-policy.md', providers: 'provider-agreement.md' };

if (!existsSync(source)) {
  console.log('[sync-legal] docs/legal not found - keeping the committed copy.');
  process.exit(0);
}
const body = Object.entries(files)
  .map(([slug, file]) => `  ${slug}: ${JSON.stringify(readFileSync(join(source, file), 'utf8').replace(/\r\n/g, '\n'))},`)
  .join('\n');
writeFileSync(target, `// Generated by scripts/sync-legal.mjs from docs/legal - edit those files, not this one.\nexport const LEGAL_MARKDOWN = {\n${body}\n} as const;\n`);
console.log('[sync-legal] wrote lib/legalContent.generated.ts');
