'use client';

import { FormEvent, useState } from 'react';
import { createClient } from '../../lib/supabase-browser';
import './polish.css';

function EyeIcon({ off = false }: { off?: boolean }) { return <svg aria-hidden="true" viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M2.5 12s3.3-5 9.5-5 9.5 5 9.5 5-3.3 5-9.5 5-9.5-5-9.5-5Z" />{!off && <circle cx="12" cy="12" r="2.2" />}{off && <path d="m4 4 16 16" />}</svg>; }

export default function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [error, setError] = useState(''); const [pending, setPending] = useState(false); const [showPassword, setShowPassword] = useState(false);
  async function signIn(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setPending(true); const { error: authError } = await createClient().auth.signInWithPassword({ email, password }); if (authError) { setError(authError.message); setPending(false); return; } window.location.assign('/verifications'); }
  return <main className="login reference-login"><section className="reference-card" aria-labelledby="login-title"><img src="/logo.jpeg" alt="Solid Connect" className="reference-icon" width={96} height={96} /><h1 id="login-title">Admin access.</h1><p className="reference-subtitle">Sign in to manage verifications, disputes,<br />and platform operations.</p><form onSubmit={signIn}><label className="reference-input"><svg aria-hidden="true" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="4" width="20" height="16" rx="2" /><path d="m2 7 10 5 10-5" /></svg><input name="email" value={email} onChange={event => setEmail(event.target.value)} type="email" autoComplete="email" placeholder="Email" aria-label="Email" required /></label><label className="reference-input"><svg aria-hidden="true" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="11" width="18" height="11" rx="2" /><path d="M7 11V7a5 5 0 0 1 10 0v4" /></svg><input name="password" value={password} onChange={event => setPassword(event.target.value)} type={showPassword ? 'text' : 'password'} autoComplete="current-password" placeholder="Password" aria-label="Password" required /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? 'Hide password' : 'Show password'}><EyeIcon off={!showPassword} /></button></label><a className="forgot-link" href="mailto:support@solidconnect.co?subject=Admin%20password%20reset">Forgot password?</a><button className="reference-submit" disabled={pending}>{pending ? 'Signing in…' : 'Sign in'}</button>{error && <p className="notice" role="alert">{error}</p>}</form><p className="login-foot">Access is limited to provisioned administrators.</p></section></main>;
}
