// Copies Leaflet (pinned in package.json devDependencies) into
// src/lib/leafletAssets.generated.ts so the map WebViews (ServiceMap,
// JobLiveMap) inline the library instead of fetching it from a CDN - no
// third-party script host sees our users' IP addresses, and nothing outside
// the app bundle can change the code that runs next to their live location.
// Run after bumping the leaflet version: `npm run sync-leaflet`. The
// generated file is committed, so builds never need node_modules/leaflet.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, '..', 'node_modules', 'leaflet');
const target = join(here, '..', 'src', 'lib', 'leafletAssets.generated.ts');

const read = (file) => readFileSync(join(pkg, file), 'utf8').replace(/\r\n/g, '\n');
const { version } = JSON.parse(read('package.json'));
const js = read('dist/leaflet.js').replace(/\n\/\/# sourceMappingURL=.*$/, '');
const css = read('dist/leaflet.css');

// Both end up inside <script>/<style> tags; a closing tag in the source
// would end the tag early and break the page.
if (/<\/script/i.test(js) || /<\/style/i.test(css)) throw new Error('Leaflet source contains a closing tag');

const license = read('LICENSE')
  .trim()
  .split('\n')
  .map((line) => ` * ${line}`.trimEnd())
  .join('\n');

writeFileSync(
  target,
  `// Generated by scripts/sync-leaflet.mjs from leaflet@${version} - do not edit.
/*
 * Leaflet ${version} - https://leafletjs.com
 *
${license}
 */
export const LEAFLET_VERSION = ${JSON.stringify(version)};
export const LEAFLET_CSS = ${JSON.stringify(css)};
export const LEAFLET_JS = ${JSON.stringify(js)};
`,
);
console.log(`[sync-leaflet] wrote src/lib/leafletAssets.generated.ts (leaflet ${version})`);
